// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAcgR3po4M-CmWU2h6F1n1tvk30z0UEQpk',
    appId: '1:742498293467:web:cc8569afc06ef2aadedefe',
    messagingSenderId: '742498293467',
    projectId: 'labtest-mystaffapp',
    authDomain: 'labtest-mystaffapp.firebaseapp.com',
    storageBucket: 'labtest-mystaffapp.firebasestorage.app',
    measurementId: 'G-T4VRJ24VRZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDoDtZuhe308g0a7InxgW3grPZjwZgdyhY',
    appId: '1:742498293467:android:292dee876cfd2188dedefe',
    messagingSenderId: '742498293467',
    projectId: 'labtest-mystaffapp',
    storageBucket: 'labtest-mystaffapp.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDduLAWvFOO49HZIfYG10QCmO6bVF9DHyI',
    appId: '1:742498293467:ios:45b2927b9665f23adedefe',
    messagingSenderId: '742498293467',
    projectId: 'labtest-mystaffapp',
    storageBucket: 'labtest-mystaffapp.firebasestorage.app',
    iosBundleId: 'com.example.mystaffapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDduLAWvFOO49HZIfYG10QCmO6bVF9DHyI',
    appId: '1:742498293467:ios:45b2927b9665f23adedefe',
    messagingSenderId: '742498293467',
    projectId: 'labtest-mystaffapp',
    storageBucket: 'labtest-mystaffapp.firebasestorage.app',
    iosBundleId: 'com.example.mystaffapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAcgR3po4M-CmWU2h6F1n1tvk30z0UEQpk',
    appId: '1:742498293467:web:7f66629a5d824d2bdedefe',
    messagingSenderId: '742498293467',
    projectId: 'labtest-mystaffapp',
    authDomain: 'labtest-mystaffapp.firebaseapp.com',
    storageBucket: 'labtest-mystaffapp.firebasestorage.app',
    measurementId: 'G-F3VVQ1DP6Y',
  );
}
